### ISSUE TITLE
speex-1.2.rc2 is not newer than speex-1.2.0  

### ISSUE THREAD

**Issue by ChrisAbela** [sbopkg/sbopkg#24]
# sbopkg -c
[ Checking for potential updates ]
This may take a few moments. Press <ESC> to abort.
100%[===========================================================================]
Listing installed SBo repository for Slackware 14.2 packages and flagging
potential updates...
speex:
  INSTALLED PACKAGE IS NEWER THAN REPO
  Installed version:  speex-1.2rc2-x86_64-5_SBo
  Repo version:  speex-1.2.0-x86_64-1_SBo

**Comment by willysr** [comment]
Hi Chris

It happened because it doesn't follow the same versioning scheme.
it should be 1.2.0rc2 instead of 1.2rc2.

in sbopkg, we define updates_compare_versions (https://github.com/sbopkg/sbopkg/blob/master/src/usr/sbin/sbopkg#L952) which compares the numeric versions. As development often stalled, people decided to package alpha, beta, or rc release, which is not suitable in SBo, but it does happened, like what we had in speex.
